source('download-extract.R')
if(!require(lattice)) {
    install.packages("lattice")
    library(lattice)
}
legendNames <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
lineData <- c(house$Sub_metering_1, house$Sub_metering_2, house$Sub_metering_3)
metering <- range(lineData)
colors <- c("black", "red", "blue")
png("plot3.png", width = 480, height = 480)
plot(x = house$datetime, y=NULL, col=colors[3], ylim = metering, type="l", ylab = "Energy sub metering", xlab = "", axes = FALSE, frame.plot = TRUE)
lines(house$Sub_metering_1, type="l", col=colors[1])
lines(house$Sub_metering_2, type="l", col=colors[2])
lines(house$Sub_metering_3, type="l", col=colors[3])
axis.Date(side = 1, house$datetime, format = "%a")
axis(side = 2, house$Sub_metering_3)
legend("topright", legendNames, col = c("black", "red", "blue"), lty = c(1,1))
dev.off()
